### ISSUE TITLE
Reduce the facet pane

### ISSUE THREAD

**Issue by ghost** [OpenWork-NZ/core-geonetwork#104]
Default is to "Collapse" categories.

Remove "CONTACT FOR THE RESOURCE", "FORMATS",  "REPRESENTATION TYPES",  "UPDATE FREQUENCIES"), "SERVICE TYPES",  "REPRESENTATION TYPES

Collapse everything except "TOPICS"

See GNS as an example:
https://data.gns.cri.nz/metadata/srv/eng/catalog.search#/search?resultType=gns_public_filters&sortBy=relevance&from=1&to=20

![image](https://github.com/OpenWork-NZ/core-geonetwork/assets/91862430/db6e1c41-5388-45ac-bf77-88cb12c7fef2)

**Comment by alcinnz** [comment]
Changes applied in GeoNetwork configuration, they are live.

0.5 hours
