### ISSUE TITLE
Coupled Resource needs more human readable names

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#11]
When expanding the tab for "Coupled Resource", the XML namespaced names are currently used. This is not user friendly.

Enhancement is to change the names to match MDWG Best Practice discussions.

**Comment by ByronCinNZ** [comment]
Additional edits throughout .../schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml to incorporate missing elements.
Will need to migrate these changes to iso19115-3:2018-icsm plugin schema
Recommend review of this file to enhance help, apply selectors, etc

**Comment by ByronCinNZ** [comment]
May revisit
