### ISSUE TITLE
Service Type

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#12]
Should not use the suggested dropdown items for Service Type. Rather should use a different vocabulary.

Enhancement: new options could be "discovery", "view", "download", "transformation", or "invoke".
This is a somewhat confusion issue. The standard lacks clarity about how this element and related elements (ServiceType, ServicewVersion, profile and ServiceStandard). More firm agreement and guidance from MDWG would be helpful as these are likely xearch parameters. Computers need to know how to find and index these values
![image](https://user-images.githubusercontent.com/1085756/94625317-f59f0200-0314-11eb-8632-3dce4bd37778.png)

**Comment by alcinnz** [comment]
#4

**Comment by ByronCinNZ** [comment]
Look to the list from Irina for appropriate dropdown options.
Option may be to use "managed Directories" to populate full fragment of service type standard version and profile

**Comment by ByronCinNZ** [comment]
Rethinking what this element, ServiceType, should hold. If I am creating a GeoNetwork catalogue and want a metadata record for this service, I would think it would be useful if this field said it was a geonetwork catalogue. Version would be in the servicetypeversion field. Service standards would be held in the Servicestandard elements.
Need feedback on this from the MDWG
