### ISSUE TITLE
Responsible Party in Manage Directory lacks ability to save identifiers for parties

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#14]
Identifiers like ORCIDs should travel with the stored contact information.
Workaround is to add it after importing stored information.
Related: Should contact information be populated in the template or encourage using the "Search for contact" option?
How do we best do this in the template?
![image](https://user-images.githubusercontent.com/1085756/94625415-30a13580-0315-11eb-9250-80ea0432328d.png)

**Comment by alcinnz** [comment]
#4

**Comment by ByronCinNZ** [comment]
When addressing issue #16 we resolved this issue
Need improved documentation for capturing metadata fragments for contacts
