### ISSUE TITLE
Display issue with Distributor

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#17]
When selecting a distributor from a Search For Contact, it leaves a misleading prompt under Distributor. Incorrectly marked mandatory, when the appropriate information is entered elsewhere.
This is inconsistent behaviour on GN

![](https://user-images.githubusercontent.com/1085756/94379370-4afbd780-018c-11eb-8e85-e81b21c39704.png)

**Comment by alcinnz** [comment]
Out-of-scope for contract, at least for now.

**Comment by ByronCinNZ** [comment]
In config-editor.xsl for ISO19115-3:2018 the location for the contact selection tool is misplaced. At line 129, "mrd:distributor" should be "mrd:distributorContact"
