### ISSUE TITLE
Distribution Information

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#18]
Recommend values for format names need review to include all the most common formats.
Note: Distribution information can be captured also in the "Associated Resources" panel under "Online Resources". guidance about which to use when may be helpful

**Comment by alcinnz** [comment]
#4

**Comment by alcinnz** [comment]
As far as I can tell, there are no longer *any* recommended format names.

**Comment by ByronCinNZ** [comment]
If we have a thesaurus holding these values, how do we get these in a codelist and make these sync?

**Comment by alcinnz** [comment]
Fixed in 193325226195807f92e60b2cfc9dbd8703b0b180 by extending the `<helper>` subelement for `cit:title` in `$schemaplugindir/loc/$lang/labels.xml`.

New entries taken from https://vocabs.ardc.edu.au/viewById/181

Could do with a review @ByronCinNZ
