### ISSUE TITLE
Associated Resources, OnlineResource is flaky

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#24]
Particularly in the "link a" field. "link a" may report the wrong thing on retrieval from associated resources, at least for "additional documentation".
Example additional issues with "Associated resources" tool

**Comment by alcinnz** [comment]
#8

**Comment by ByronCinNZ** [comment]
Associated Resources should be renamed to "Linked Resources" as associated resource has particular meaning as a ISO 19115 element

**Comment by alcinnz** [comment]
Merge with #38

Unclear what the issue we were having here is, it *might* have been fixed in latest geonetwork.

**Comment by alcinnz** [comment]
When linking a dataset to a service creates a record for both "Coupled Resource" & "Operates On". In "Full View" (nonedit) the name displayed for that "operates on" record is incorrect.

This seems to relate to the `view.xsl` file line 1002, calling `gn-fn-render:getMetadataTitle()`. The confusing thing here is that the ID passed is the same that correctly populates the `href` for the link. We're unclear where this XPath function is defined.

**Comment by alcinnz** [comment]
- [x] Label changes:
"Name of Coupled Resource" -> "Scoped Name"
"Website" -> "Online Linkage"
"OnLine resource" -> "Online resource"

- [x] When you link a dataset to service it should autopopulate "Scoped Name", "Citation Title", Citation Online Linkage & Description (should read "Metadata for ...") as according to MDWG guidance for Coupled Resource.

- [x] Also enable Coupled Resource to be populated through selection of a dataset, currently only Operates On gets populated.

**Comment by alcinnz** [comment]
Changed the $schema/loc/eng/labels.xml to fix poor labelling.

**Comment by alcinnz** [comment]
Files of interest:

* `web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js` is the main UI file for add link to service dialog.
* `components/catalog/CatalogService.js` provides some indication of available metadata fields.
* `resources/catalog/edit/EditorController.js` sets many of the fields on the `gnCurrentEdit` global.

**Comment by alcinnz** [comment]
We captured the abstract in `EditorController.js` & stored it in `gnCurrentEdit`.

**Comment by alcinnz** [comment]
Cleanup passing information for abstract.

**Comment by ByronCinNZ** [comment]
Issue done for now. Likely need to revisit some aspects for workflow and styling
