### ISSUE TITLE
Create a system to populate license information

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#25]
Source from a managed directory like "Organizations & contacts".
There seems to be a Search For Constraint option, but cannot figure out how to make it work. An autocompletion list flashes onscreen with a spinner, but never yields any results.

**Comment by alcinnz** [comment]
#4

**Comment by ByronCinNZ** [comment]
Basic issue solved  - can now populate with legal constraints sourced from managed directory.
Still need to

- [ ] populate Legal constraints with some common constraints, e.g. the various CC licenses
- [ ] Create a template for security constraints and populate it with Australian security classifications
- [ ] Create a template for other constraints and populate it with some common usages, e.g. "Not to be used for navigation", "For non-commercial purposes only"
