### ISSUE TITLE
Thesaurus support

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#3]
The thesaurus support system is a valuable way to capture keywords. But it has a number of issues:

- [x] Seems not to have been migrated to 19115-3 and still uses 19139 schemas. Several sub-issues are likely the result of this 
- [x] - Document uploading SKOS for the provided links.
- [x] - Keyword Class does not seem to travel with the thesaurus entry. This is likely due to thesaurus support not being udated from 139 to 115-3
- [x] - records populated through a thesaurus are not labeled as keywords in the interface. General look and feel improvements could be made to sections popupated this way.
- [x] - Keyword typecode is not complete to 19115-3. Likely due to nonmigration to 19115-3
- [x] - loading thesaurus is problematic and often partial with little indication of what went wrong or how to fix.
- [x] - compute extents from placename keywords are not functioning. Could be related to mismatch 139 and 115-3?

![image](https://user-images.githubusercontent.com/1085756/94624448-fafb4d00-0312-11eb-9d68-10404c951ef8.png)

**Comment by ByronCinNZ** [comment]
Task 2 and four in tranche 1
Subtask the bulleted items

**Comment by ByronCinNZ** [comment]
Corrected many portions of this issue

- Managed to import SKOS schemas by
  - Downloading CSV from from Inspire http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory
  - Reformatting and exporting to spreadsheet following instructions at https://skos-play.sparna.fr/play/
    - Ensure rows are split by "|".
    - Rename appropriate columns to URI, skos:prefLabel, dct:title (necessary for correct labelling), skos:definition, skos:broader, etc.
    - Ensure presence of a "header" with "ConceptScheme URI" in A1 & "http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory" in B1.
  - Loading via GN Thesaurus upload from file function
  - Need 
    - to review options to enhance use of this thesaurus to populate more fields
    - Better document process
- Extended the keyword typecode list to include all options from ISO19115-3
  - (Adrian to provide Details)
- Other issues remain

**Comment by alcinnz** [comment]
Studying the code, GeoNetwork's constraint on SKOS files appears to be:

There must be a <skos:ConceptScheme> or <skos:Collection> element containing Dublin Core or Dublin Core Terms properties as subelements for the title & issued date.

**Comment by ByronCinNZ** [comment]
Add extent from keyword call -
http://localhost:8080/geonetwork/srv/api/records/141/processes/add-extent-from-geokeywords?process=add-extent-from-geokeywords&replace&id=141

**Comment by alcinnz** [comment]
All the SKOS Irina linked to works perfectly fine in GeoNetwork!

From the vocabulary's page, click "Download >" -> "RDF/XML".

In GeoNetwork once logged in as admin click "Admin console" -> "Classification Systems" -> "+ Add thesaurus" -> "From local file". In the opened dialog select the file you have just downloaded & select a keyword type from the dropdown. Click "Upload".

The thesaurus should appear in the sidebar, and upon clicking it you should see a listing of all it's terms.

---

Tested vocabularies include:

* https://vocabs.ardc.edu.au/viewById/181
* https://vocabs.ardc.edu.au/viewById/180
* https://vocabs.ardc.edu.au/viewById/177
* https://vocabs.ardc.edu.au/viewById/184
