### ISSUE TITLE
Non-English terms e.g. "Addresse" is misspelled

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#34]
Some terms are not English. Need to review and fix in localisation

words with macrons such as “references” and “Series”

**Comment by alcinnz** [comment]
I'm not *entirely* sure where to check for these misspellings, but from what I can tell I think this is solved!

**Comment by alcinnz** [comment]
After a *more* thorough search I don't see "address" or "series" being misspelled but I do, but I do see reference being spelled as "Référence".

**Comment by ByronCinNZ** [comment]
Minor corrections throughout .../schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/labels.xml
Will need to migrate these changes to iso19115-3:2018-icsm plugin schema 
Recommend review of this file to enhance help, apply selectors, etc.
