### ISSUE TITLE
Metadata identifier

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#36]
Difficult to figure out how to setup a custom URN. They do have instructions https://geonetwork-opensource.org/manuals/trunk/en/administrator-guide/managing-metadata-standards/metadata-identifier.html The functionality also appears to be broken. URN templates seem not to be working.

Weakness: It doesn't allow us to automatically create an authority for the metadata.

We're still getting a GN-generated UUID instead of a custom one.

The codespace has an unchangable value of urn:uuid.

As per conversation with Francois Prunya the recommendation of using the codespace to hold the root namespace cannot be done.
Shortterm actions: use MetadataLinkage to hold the resolvable URI UUID.

Make sure when harvested by Dublin Core & similar catalogues that this maps to ID.
Medium term: See if you can fix the custom UUID.
Long term: Resolve larger issues around UUID assignment & relationship to URL. Needs to be easy for the user.

Template needs more automation for custom UUIDs. e.g. attach autogenerated UUID to custom namespace.
Issues:

- The custom identifier option seems non-functional
- CodeSpace value cannot be modified.

Time : 24h

- [x] Ensure custom URN works in ISO 19115-3 (Does it work in ISO19139?)
- [ ] Remove protection of Codespace so base URL can be supplied
- [x] Document full process well.

Remainder of issues above out of scope of editor.

**Comment by alcinnz** [comment]
Documentation link appears to be broken, even when fixing the obvious "trunk" typo.

**Comment by alcinnz** [comment]
The documentation definitely needs to be updated. I'm not sure there's an issue with the ability to define new custom identifiers but there is an issue in setting them.

**Comment by alcinnz** [comment]
Part of the issue is that we were failing to save the new settings. Novice mistake.

But now that we can set custom URNs, they won't populate. That'll require digging into the code.

**Comment by ByronCinNZ** [comment]
Codespace value for Metadata identifier now works by getting the full url minus the uuid. This is the default default. Still an uneditable field. Discussions need to be had with MDWG and GN Dev team as to where to go with this.
