### ISSUE TITLE
Managed Directory

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#4]
The "Manage directory" interface on the editor board is a great place to store contacts. But it could be used for much more e.g. Constraint info. distribution formats, standards. It currently holds a non functional distribution info section that is not referenced by the metadata (Whether it would be useful is unclear as the cdownload link would have to change for each entry.) 
Many issues are related to this:
- Lack of support or documentation for additional packages e.g. constraints, formats, standards
- Location of tool logically should be alongside thesaurus
- May be issues of alignment with 19139 rather than 19115-3
![image](https://user-images.githubusercontent.com/1085756/94625063-5da11880-0314-11eb-9601-74958b247464.png)
![image](https://user-images.githubusercontent.com/1085756/94625139-8a553000-0314-11eb-8a48-fe7c33691f05.png)

**Comment by alcinnz** [comment]
Types of entries have been expanded to include:

* cit:CI_Organization (non-localized)
* Organizations & Contacts
* Online Resources
* mdb:MD_Metadata

**Comment by ByronCinNZ** [comment]
- [ ] Document the process for creating a managed directory for a metadata fragment. Include subtemplate creation, linkage to a field, etc. Reference all files that need to be modified.
