### ISSUE TITLE
Constraint information

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#40]
A useful enhancement would be to source "Constraints" fragments in a managed directory similar to "Organizations & contacts”. We recommend storage of Australian PSPF fragments in an extended extending managed directories service. Also, licenses such a CC versions should be supported.These fragments could be retrieved as needed for a metadata record section.

**Comment by alcinnz** [comment]
Not fixed in latest GN, only has dropdown at a more abstract level.

**Comment by ByronCinNZ** [comment]
See issue #25
