### ISSUE TITLE
Keywords: Continents, countries, sea regions of the world

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#60]
This should be using the SCAR Gazzeter: [SCAR Composite Gazetteer (aad.gov.au)](https://data.aad.gov.au/aadc/gaz/scar/)

**Comment by ByronCinNZ** [comment]
Will remove and use alternative list as per recent guidance from Francois

**Comment by alcinnz** [comment]
Duplicate with #73, low-priority
