### ISSUE TITLE
Keywords For Service

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#7]
The domain list from ISO19119 is not available.
GN enhancement - upload the 19119 codelist to a thesaurus of type keyword.
We did this in our repository but it needs to be of keyword type "service" which was unavailable - see issue #6

**Comment by alcinnz** [comment]
#3

**Comment by ByronCinNZ** [comment]
This differs from issue #3 as it is about 119 not 139

**Comment by alcinnz** [comment]
Successfully managed to import these keywords by downloading TSV for the ontology & rearranging it into something [SKOS Play](https://skos-play.sparna.fr/play/convert) can convert into a SKOS file structured how GeoNetwork expects.

**Comment by ByronCinNZ** [comment]
Next steps are to review possible enhancements to the Thesaurus to populate additional fields when keyword is added.

**Comment by ByronCinNZ** [comment]
Sprint 2  improvements - like the special use case for keyword type "place", create an interface for keyword type "Service" that pulls in the 19119 list to choose from. Look at "layout-custom-fields-keywords.xsl" in the 19115-3:2018 plugin to edit to this purpose

**Comment by ByronCinNZ** [comment]
Rethinking what this element should hold. If I am creating a GeoNetwork catalogue and want a metadata record for this service, I would think it would be useful if this field said it was a geonetwork catalogue. Version would be in the servicetypeversion field. Service standards would be held in the Servicestandard elements.
Need feedback on this from the MDWG
