### ISSUE TITLE
JSON  "@type":"DataDownload": "encodingFormat": "WWW:DOWNLOAD-1.0-http--download" 

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#77]
this is being defined as protocol in the XML file, and encoding format in the JSON. The encoding format is the file type? e.g. netcdf, audio/mpeg. https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#distributions

**Comment by ByronCinNZ** [comment]
May been corrected. Need confirmation

**Comment by alcinnz** [comment]
Duplicate with #76 ?

**Comment by ghost** [comment]
Correct. Let's remove this item.
