### ISSUE TITLE
Coupled Resource

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#9]
The "Associated resources" box provides a way to link a resource to a dataset. This puts the link in the wrong spot.

It's in the sidebar section, but "Add linko a dataset" puts it in "operatesOn".
The associated resource tool in Geonetwork should provide a way to link a coupled dataset to the service. But it does not, at least not correctly.

"Link to a dataset", "Link to a source dataset" neither of these put anything in the metadata itself. Link to an online resource does, but it puts it in "operates on" rather than "coupled resource".

**Comment by alcinnz** [comment]
#8

**Comment by ByronCinNZ** [comment]
May be fixed in latest release

**Comment by ByronCinNZ** [comment]
Combined with #24 
Associated resource now populates CoupledResource. But more work to do.
Populating from the service opulates the title with the service resource name not the dataset name 
Issues retaining the assosciate resource in the associated resource box.
