### ISSUE TITLE
Create requested usergroups

### ISSUE THREAD

**Issue by alcinnz** [OpenWork-NZ/core-geonetwork#93]
As discussed, could you please use your admin account to setup these groups and edit the current naming of “AntarcticaNZ”:
 
 • AntarcticaNZ --> Antarctica New Zealand
 • Antarctic Science Platform
 • National Modelling Hub
 • Antarctic Heritage Trust
 • *remove Sample Group

**Comment by alcinnz** [comment]
Also create an administration group?

(above groups have already been created)

**Comment by ByronCinNZ** [comment]
Adrian 23-3-23 .5 hours
