### ISSUE TITLE
Verify Site Ownership

### ISSUE THREAD

**Issue by ghost** [OpenWork-NZ/core-geonetwork#96]
Upload html verification file to the catalogue's root directory.

This probably should be done through an Antarctica NZ Google account to ensure long-term access.

Go via URL Prefix:
https://search.google.com/search-console/welcome

And confirm that Google will use the appropriate image in the search results:

This needs to be the logo that includes "Antarctica New Zealand" text:

![ANZ_Logo_Stacked_CMYK](https://user-images.githubusercontent.com/91862430/231326470-6aee64c3-a3cc-4b9a-aa22-c974b7664cc8.jpg)

**Comment by alcinnz** [comment]
15min, verification file deployed!
