### ISSUE TITLE
"Download and links" - Missing Distribution Metadata

### ISSUE THREAD

**Issue by ghost** [OpenWork-NZ/core-geonetwork#97]
The Distribution Metadata has been removed/only the data link is being shown.

See:
https://ant-nz.geodata.nz/geonetwork/srv/eng/catalog.search#/metadata/4a38ad3e-f0c9-4bf1-acd5-173ed41360a4

![image](https://user-images.githubusercontent.com/91862430/231303762-20e4f6a9-b277-4ac1-8d11-c7259253c5cc.png)

**Comment by ByronCinNZ** [comment]
Could you please give more details about the desired behaviour? By "Distribution Metadata", do you mean a link to the point of truth metadata record, or additional metadata about the distribution source? How would you like this information to be displayed? Is this related to #89?

**Comment by ghost** [comment]
That's correct, the Distribution Metadata/Source of Truth Metadata is not displaying.

When I add the Distribution Metadata/Source of Truth Metadata to the form:
![image](https://user-images.githubusercontent.com/91862430/233868812-58b77aad-eb87-4d64-917e-1d2b5eb4d7f2.png)

I get this:
https://antcat.antarcticanz.govt.nz/geonetwork/srv/eng/catalog.search#/metadata/71735ff4-09b0-4119-a28a-ab5ccc03d095
![image](https://user-images.githubusercontent.com/91862430/233868884-93645a4b-edf6-4e6f-9644-3dd937018d03.png)

When I would expect to get this (old record before the Datalink was added):
https://antcat.antarcticanz.govt.nz/geonetwork/srv/eng/catalog.search#/metadata/20455005-2e51-47e4-8eb9-76ec888f5d72
![image](https://user-images.githubusercontent.com/91862430/233868738-4b64c92e-e92c-40ca-acc9-3392781df678.png)

**Comment by ByronCinNZ** [comment]
To get the metadata link in that section, a linked record was created under distribution using the "Link an online resource" tool -
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/1085756/233885307-8a8ef25a-d3a8-46f0-b688-d39d25fd47b0.png">
To populate a similar link using the the contents of the mdb:metadataLinkage element (Point of Truth metadata) would require some more involved modifications and upkeep into the future.

**Comment by ghost** [comment]
Park for now.
